import tableavatar from '../../../../../public/tableavatar.png';

const data = [
  {
    id: 1,
    name: 'John Doe',
    avatar: tableavatar, // Directly assign the imported image
    phone: '+1234567890',
    tier: 'Premium',
    subscriptionId: 'SUB-1234',
    features: 'Feature A',
    upcomingRenewals: '1 month',
    amount: '$10',
  },
  {
    id: 2,
    name: 'Jane Smith',
    avatar: tableavatar, // Directly assign the imported image
    phone: '+0987654321',
    tier: 'Basic',
    subscriptionId: 'SUB-5678',
    features: 'Feature C',
    upcomingRenewals: '3 months',
    amount: '$20',
  },
  {
    id: 3,
    name: 'Alice Johnson',
    avatar: tableavatar,
    phone: '+1122334455',
    tier: 'Standard',
    subscriptionId: 'SUB-9101',
    features: 'Feature B',
    upcomingRenewals: '2 months',
    amount: '$15',
  },
  {
    id: 4,
    name: 'Bob Brown',
    avatar: tableavatar,
    phone: '+2233445566',
    tier: 'Premium',
    subscriptionId: 'SUB-1121',
    features: 'Feature D',
    upcomingRenewals: '1 month',
    amount: '$12',
  },
  {
    id: 5,
    name: 'Charlie Davis',
    avatar: tableavatar,
    phone: '+3344556677',
    tier: 'Basic',
    subscriptionId: 'SUB-3141',
    features: 'Feature E',
    upcomingRenewals: '4 months',
    amount: '$18',
  },
  {
    id: 6,
    name: 'Dana White',
    avatar: tableavatar,
    phone: '+4455667788',
    tier: 'Standard',
    subscriptionId: 'SUB-5161',
    features: 'Feature F',
    upcomingRenewals: '6 months',
    amount: '$22',
  },
  {
    id: 7,
    name: 'Eve Black',
    avatar: tableavatar,
    phone: '+5566778899',
    tier: 'Premium',
    subscriptionId: 'SUB-7181',
    features: 'Feature G',
    upcomingRenewals: '3 months',
    amount: '$30',
  },
  {
    id: 8,
    name: 'Frank Green',
    avatar: tableavatar,
    phone: '+6677889900',
    tier: 'Basic',
    subscriptionId: 'SUB-8202',
    features: 'Feature H',
    upcomingRenewals: '2 months',
    amount: '$14',
  },
  {
    id: 9,
    name: 'Grace Lee',
    avatar: tableavatar,
    phone: '+7788990011',
    tier: 'Standard',
    subscriptionId: 'SUB-9213',
    features: 'Feature I',
    upcomingRenewals: '1 month',
    amount: '$19',
  },
  {
    id: 10,
    name: 'Hank Wilson',
    avatar: tableavatar,
    phone: '+8899001122',
    tier: 'Premium',
    subscriptionId: 'SUB-1021',
    features: 'Feature J',
    upcomingRenewals: '6 months',
    amount: '$25',
  },
  {
    id: 1,
    name: 'John Doe',
    avatar: tableavatar, // Directly assign the imported image
    phone: '+1234567890',
    tier: 'Premium',
    subscriptionId: 'SUB-1234',
    features: 'Feature A',
    upcomingRenewals: '1 month',
    amount: '$10',
  },
  {
    id: 2,
    name: 'Jane Smith',
    avatar: tableavatar, // Directly assign the imported image
    phone: '+0987654321',
    tier: 'Basic',
    subscriptionId: 'SUB-5678',
    features: 'Feature C',
    upcomingRenewals: '3 months',
    amount: '$20',
  },
  {
    id: 3,
    name: 'Alice Johnson',
    avatar: tableavatar,
    phone: '+1122334455',
    tier: 'Standard',
    subscriptionId: 'SUB-9101',
    features: 'Feature B',
    upcomingRenewals: '2 months',
    amount: '$15',
  },
  {
    id: 4,
    name: 'Bob Brown',
    avatar: tableavatar,
    phone: '+2233445566',
    tier: 'Premium',
    subscriptionId: 'SUB-1121',
    features: 'Feature D',
    upcomingRenewals: '1 month',
    amount: '$12',
  },
  {
    id: 5,
    name: 'Charlie Davis',
    avatar: tableavatar,
    phone: '+3344556677',
    tier: 'Basic',
    subscriptionId: 'SUB-3141',
    features: 'Feature E',
    upcomingRenewals: '4 months',
    amount: '$18',
  },
  {
    id: 6,
    name: 'Dana White',
    avatar: tableavatar,
    phone: '+4455667788',
    tier: 'Standard',
    subscriptionId: 'SUB-5161',
    features: 'Feature F',
    upcomingRenewals: '6 months',
    amount: '$22',
  },
  {
    id: 7,
    name: 'Eve Black',
    avatar: tableavatar,
    phone: '+5566778899',
    tier: 'Premium',
    subscriptionId: 'SUB-7181',
    features: 'Feature G',
    upcomingRenewals: '3 months',
    amount: '$30',
  },
  {
    id: 8,
    name: 'Frank Green',
    avatar: tableavatar,
    phone: '+6677889900',
    tier: 'Basic',
    subscriptionId: 'SUB-8202',
    features: 'Feature H',
    upcomingRenewals: '2 months',
    amount: '$14',
  },
  {
    id: 9,
    name: 'Grace Lee',
    avatar: tableavatar,
    phone: '+7788990011',
    tier: 'Standard',
    subscriptionId: 'SUB-9213',
    features: 'Feature I',
    upcomingRenewals: '1 month',
    amount: '$19',
  },
  {
    id: 10,
    name: 'Hank Wilson',
    avatar: tableavatar,
    phone: '+8899001122',
    tier: 'Premium',
    subscriptionId: 'SUB-1021',
    features: 'Feature J',
    upcomingRenewals: '6 months',
    amount: '$25',
  },
];

export default data;
